# https://www.mkdocs.org/user-guide/configuration/

# Project information
site_name: xdsl-template                                                        # TODO: Change this
site_author: xDSL Developers                                                    # TODO: Change this
copyright: Copyright &copy xDSL Developers                                      # TODO: Change this

# Repository
repo_name: xdsl/xdsl-template                                                   # TODO: Change this
repo_url: https://github.com/xdsl/xdsl-template                                 # TODO: Change this

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xdsl                                             # TODO: Change this
      name: xDSL on Github                                                      # TODO: Change this


# Configuration
use_directory_urls: false

nav:
  - Home: index.md
  - Reference: reference.md

theme:
  name: material
  locale: en_GB
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  # Inbuilt extensions
  # https://python-markdown.github.io/extensions/
  - admonition
  - footnotes
  - meta
  - sane_lists
  - smarty
  - tables
  - toc:
      permalink: true
  # Third party extensions
  # https://facelessuser.github.io/pymdown-extensions/
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
