from xdsl.ir import Dialect

from .attributes import (
    ComparisonDirectionAttr,
    ComparisonTypeAttr,
    CustomCallApiVersionAttr,
    DotAttr,
    GatherDimensionNumbers,
    OutputOperandAlias,
    PrecisionAttr,
    ResultAccuracyModeAttr,
    ScatterDimensionNumbers,
    TokenType,
)
from .elementwise_unary_ops import (
    CbrtOp,
    CeilOp,
    ConvertOp,
    CountLeadingZerosOp,
    FloorOp,
    IsFiniteOp,
    NotOp,
    PopcntOp,
    RoundNearestAfzOp,
    RoundNearestEvenOp,
    RsqrtOp,
    SqrtOp,
)
from .ops import (
    AbsOp,
    AddOp,
    AfterAllOp,
    AndOp,
    Atan2Op,
    BitcastConvertOp,
    CaseOp,
    ConstantOp,
    MultiplyOp,
    OrOp,
    PadOp,
    ReturnOp,
    ShiftLeftOp,
    ShiftRightArithmeticOp,
    ShiftRightLogicalOp,
    SubtractOp,
    TransposeOp,
    XorOp,
)

StableHLO = Dialect(
    "stablehlo",
    [
        # Elementwise unary operations
        CbrtOp,
        CeilOp,
        ConvertOp,
        CountLeadingZerosOp,
        IsFiniteOp,
        FloorOp,
        NotOp,
        PopcntOp,
        RoundNearestAfzOp,
        RoundNearestEvenOp,
        RsqrtOp,
        SqrtOp,
        # Other operations
        AbsOp,
        AddOp,
        AfterAllOp,
        AndOp,
        Atan2Op,
        BitcastConvertOp,
        CaseOp,
        ConstantOp,
        MultiplyOp,
        OrOp,
        PadOp,
        ReturnOp,
        ShiftLeftOp,
        ShiftRightArithmeticOp,
        ShiftRightLogicalOp,
        SubtractOp,
        TransposeOp,
        XorOp,
    ],
    [
        ComparisonDirectionAttr,
        ComparisonTypeAttr,
        CustomCallApiVersionAttr,
        DotAttr,
        GatherDimensionNumbers,
        OutputOperandAlias,
        PrecisionAttr,
        ResultAccuracyModeAttr,
        ScatterDimensionNumbers,
        TokenType,
    ],
)

__all__ = ["StableHLO"]
