name: repo-sync

# Doc: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  schedule:
    - cron:  "0 1 * * MON"
  # Allow this workflow to be manually triggered
  workflow_dispatch:

env:
  SOURCE_BRANCH: main
  SOURCE_REPOSITORY: xdslproject/xdsl-template

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Doc: https://github.com/marketplace/actions/checkout
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v5
        if: github.repository != env.SOURCE_REPOSITORY
        with:
          persist-credentials: false # needed in case workflows are updated

      # Doc: https://github.com/marketplace/actions/actions-template-sync
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2.5.2
        if: github.repository != env.SOURCE_REPOSITORY
        with:
          source_repo_path: ${{ env.SOURCE_REPOSITORY }}
          upstream_branch: ${{ env.SOURCE_BRANCH }}
          pr_title: "misc: Update template"
          pr_commit_msg: "misc: Update template"
          target_gh_token: ${{ secrets.UPDATE_TEMPLATE_TOKEN }}
